### ISSUE TITLE
How can I compile it?

### ISSUE THREAD

**Issue by shivaang12** [echau01/Minecraft-Manhunt#1]
I am really interested in this plugin. It would be helpful if you can tell mw how can I compile it to a JAR file.

**Comment by echau01** [comment]
If you want to just download the JAR file, you can download it ![here](https://github.com/echau01/Minecraft-Manhunt/releases/tag/v0.1.1-beta).

If you want to actually compile from the source code, you can just clone the repository, import it into an IDE (like IntelliJ) and build a JAR. The repo has all the required libraries.

**Comment by shivaang12** [comment]
Thanks for the reply. I was thinking if this could work in nether.

**Comment by echau01** [comment]
The compass doesn't work in the Nether; it just spins around randomly like in normal Minecraft. At least, that's what I found when I tested the plugin on 1.16.2. Do you want the compass to work in the Nether?

**Comment by shivaang12** [comment]
Thanks for the reply! Yes, I want to make it work in the nether too. Actually I am new in the "minecraft plugin universe" so I don't know much about the APIs and all. But if you know how to do it then it would be helpful if you can guide me.

**Comment by echau01** [comment]
I've just added a command ```/togglenethertracking``` that toggles the ability of the compass to work in the Nether. It's available in release v0.2.0-beta.

**Comment by shivaang12** [comment]
Thank you so much! Also let me know if you want to join my server. We are a decent crowd (7-8 active people) in survival world. I think you would love it!

**Comment by echau01** [comment]
I don't think I'll join, but thanks for the offer!

**Comment by shivaang12** [comment]
No worries, let me know if you change ur mind.
